//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaElektronika.Lang.PSC_ETH {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonPanel() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaElektronika.Lang.PSC_ETH.CommonPanel", typeof(CommonPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear.
        /// </summary>
        internal static string btClear_Text {
            get {
                return ResourceManager.GetString("btClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Calibration.
        /// </summary>
        internal static string Calibration_caption {
            get {
                return ResourceManager.GetString("Calibration_caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recall calibtation?.
        /// </summary>
        internal static string Calibration_message {
            get {
                return ResourceManager.GetString("Calibration_message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instrument ID.
        /// </summary>
        internal static string gbIDN_Text {
            get {
                return ResourceManager.GetString("gbIDN_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manufacturer:.
        /// </summary>
        internal static string lbManufacturer_Text {
            get {
                return ResourceManager.GetString("lbManufacturer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Model:.
        /// </summary>
        internal static string lbModel_Text {
            get {
                return ResourceManager.GetString("lbModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recall calibration:.
        /// </summary>
        internal static string lbRecallCalibration_Text {
            get {
                return ResourceManager.GetString("lbRecallCalibration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restore to def.:.
        /// </summary>
        internal static string lbResotre_Text {
            get {
                return ResourceManager.GetString("lbResotre_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Revision code:.
        /// </summary>
        internal static string lbRevisionCode_Text {
            get {
                return ResourceManager.GetString("lbRevisionCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serial number:.
        /// </summary>
        internal static string lbSerialNumber_Text {
            get {
                return ResourceManager.GetString("lbSerialNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Common commands.
        /// </summary>
        internal static string lbTitle_Text {
            get {
                return ResourceManager.GetString("lbTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Protected user data:.
        /// </summary>
        internal static string lbUserData_Text {
            get {
                return ResourceManager.GetString("lbUserData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Protected user data.
        /// </summary>
        internal static string PUD_caption {
            get {
                return ResourceManager.GetString("PUD_caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overwrite protected user data?.
        /// </summary>
        internal static string PUD_message {
            get {
                return ResourceManager.GetString("PUD_message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resotre to default.
        /// </summary>
        internal static string Restore_caption {
            get {
                return ResourceManager.GetString("Restore_caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restore to default state?.
        /// </summary>
        internal static string Restore_message {
            get {
                return ResourceManager.GetString("Restore_message", resourceCulture);
            }
        }
    }
}
